M48
; DRILL file {KiCad 7.0.8} date 2024 April 22, Monday 21:24:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-22T21:24:55+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.152
%
G90
G05
T1
X144.61Y-55.1
X150.39Y-55.1
T2
X122.0Y-85.0
X147.5Y-120.0
X152.5Y-65.0
X166.0Y-52.0
T0
M30
